BEIS-Digital-Services/RedBox-AWS

redbox-core/redbox/models/settings.py
=> bugfix for opensearch client

docker-compose.yml, redbox-core/pyproject.toml, redbox-core/redbox/chains/components.py, redbox-core/redbox/graph/nodes/tools.py, redbox-core/redbox/models/settings.py, redbox-core/redbox/retriever/__init__.py, redbox-core/redbox/retriever/retrievers.py
=> Opensearch implementation

django_app/Dockerfile
=> dockerfile changes

redbox-core/redbox/loader/ingester.py, redbox-core/redbox/retriever/retrievers.py
=> OpenSearch fixes

redbox-core/redbox/loader/ingester.py
=> Change environment import

django_app/Dockerfile, django_app/frontend/src/styles.scss
=> bumped node version

redbox-core/redbox/retriever/retrievers.py
=> Switch to from elastic to opensearch scan

redbox-core/redbox/models/settings.py
=> Fix for JSON Embedder formatting

redbox-core/redbox/models/settings.py
Reverts BEIS-Digital-Services/RedBox-AWS#17
=> Revert "Fix for JSON Embedder formatting"

redbox-core/redbox/loader/ingester.py, redbox-core/redbox/models/settings.py
=> Test sequential execution instead of RunnableParallel

redbox-core/redbox/loader/ingester.py
=> Added logs during ingestion

redbox-core/redbox/models/settings.py
=> Added logs to client & freeze credentials

redbox-core/redbox/loader/ingester.py, redbox-core/redbox/loader/loaders.py
=> Validate JSON format 2

redbox-core/redbox/loader/ingester.py
=> Convert raw_metdata to JSON string

redbox-core/redbox/loader/loaders.py
=> Log metadata

redbox-core/redbox/loader/loaders.py
=> Validate JSON format 3

redbox-core/redbox/loader/ingester.py
=> Add RunnableParallel back

django_app/redbox_app/redbox_core/management/commands/add_es_alias.py, django_app/redbox_app/redbox_core/management/commands/change_es_aliased_index.py, django_app/redbox_app/redbox_core/management/commands/delete_es_indices.py, django_app/redbox_app/redbox_core/management/commands/reingest_files.py, django_app/redbox_app/redbox_core/models.py, redbox-core/redbox/app.py, redbox-core/redbox/chains/components.py, redbox-core/redbox/loader/ingester.py, redbox-core/redbox/models/settings.py
=> Logging every client request to verify auth

redbox-core/redbox/models/settings.py
=> Removing client cache

redbox-core/redbox/loader/ingester.py, redbox-core/redbox/models/settings.py
=> Return authentication details from client

redbox-core/redbox/models/settings.py
=> Attempt to print OpenSearch indexes

redbox-core/redbox/models/settings.py
=> Don't freeze credentials

redbox-core/redbox/models/settings.py
=> Switch service to opensearch serverless

django_app/poetry.lock, django_app/pyproject.toml, docker-compose.yml, redbox-core/pyproject.toml, redbox-core/redbox/models/settings.py
=> Aws4 auth implementation

redbox-core/redbox/models/settings.py
=> Strip out https

django_app/redbox_app/redbox_core/models.py
=> Remove id in es_client.create

redbox-core/redbox/models/settings.py
=> Swap to regular opensearch

django_app/redbox_app/redbox_core/models.py
=> hotfix to use id

django_app/redbox_app/redbox_core/models.py, redbox-core/redbox/models/settings.py
Reverts BEIS-Digital-Services/RedBox-AWS#44
=> Revert "swap to serverless"

django_app/redbox_app/oidc_auth.py, django_app/redbox_app/redbox_core/forms.py, django_app/redbox_app/redbox_core/middleware.py, django_app/redbox_app/redbox_core/views/signup_views.py, django_app/redbox_app/settings.py, django_app/redbox_app/templates/sign-up-page-1.html
=> Show sign in pages

django_app/frontend/src/js/web-components/chats/exit-feedback.js
=> Fixed feedback bug

django_app/frontend/src/js/web-components/chats/exit-feedback.js
=> extract chat id correctly

redbox-core/redbox/models/settings.py
=> Use BasicAuth for OpenSearch

redbox-core/redbox/models/settings.py
=> Trigger new deployment

redbox-core/redbox/models/settings.py
=> hardcoding port correctly

redbox-core/redbox/loader/ingester.py, redbox-core/redbox/models/settings.py
=> Construct OS URL with basic auth in ingestor

redbox-core/redbox/chains/components.py, redbox-core/redbox/chains/runnables.py, redbox-core/redbox/loader/ingester.py, redbox-core/redbox/models/settings.py, redbox-core/redbox/retriever/queries.py, redbox-core/redbox/transform.py
=> Implement DBT changes

django_app/redbox_app/redbox_core/consumers.py, redbox-core/redbox/retriever/queries.py
=> Adding extra logs

django_app/redbox_app/redbox_core/consumers.py
=> fix error introduced from log

django_app/redbox_app/redbox_core/models.py
=> Fix NoneType error in newest_message_date

django_app/redbox_app/redbox_core/consumers.py
=> Resolve exception when printing permitted files

django_app/redbox_app/redbox_core/consumers.py
=> sync_to_async wrapper

redbox-core/redbox/graph/nodes/processes.py
=> Force test document retrieval

redbox-core/redbox/models/settings.py
=> changed env var

redbox-core/redbox/models/settings.py
=> added var for opensearch host

django_app/frontend/src/js/web-components/chats/exit-feedback.js, django_app/redbox_app/oidc_auth.py
=> bringing across changes

redbox-core/redbox/loader/ingester.py, redbox-core/redbox/models/settings.py
=> Revert to basic auth

django_app/redbox_app/redbox_core/management/commands/add_es_alias.py, django_app/redbox_app/redbox_core/management/commands/change_es_aliased_index.py, django_app/redbox_app/redbox_core/management/commands/delete_es_indices.py, django_app/redbox_app/redbox_core/management/commands/reingest_files.py, django_app/redbox_app/redbox_core/models.py, redbox-core/redbox/app.py, redbox-core/redbox/chains/components.py, redbox-core/redbox/chains/ingest.py, redbox-core/redbox/graph/nodes/tools.py, redbox-core/redbox/loader/ingester.py, redbox-core/redbox/loader/loaders.py, redbox-core/redbox/models/settings.py, redbox-core/redbox/retriever/retrievers.py
=> Added more logs

redbox-core/redbox/graph/nodes/tools.py
=> fix value error

redbox-core/redbox/loader/ingester.py
=> match correct REST path for alias check

redbox-core/redbox/loader/ingester.py
=> actually match correct REST path for alias check

django_app/redbox_app/redbox_core/models.py, redbox-core/redbox/chains/components.py, redbox-core/redbox/graph/nodes/tools.py, redbox-core/redbox/loader/ingester.py, redbox-core/redbox/models/settings.py, redbox-core/redbox/retriever/retrievers.py
=> Added 403 decorator

redbox-core/redbox/loader/ingester.py
=> Adding extra logging for _ingest_file

redbox-core/redbox/chains/ingest.py, redbox-core/redbox/loader/ingester.py
=> exception handling ingest functions

redbox-core/redbox/chains/ingest.py
=> Added logging during vectorstore.add_documents

redbox-core/redbox/chains/ingest.py
=> additional checks before vectorstore.add_documents to debug auth error

redbox-core/redbox/chains/ingest.py
=> remove index check

redbox-core/redbox/chains/ingest.py
=> verify iam role before vectorstore.add_documents

redbox-core/redbox/chains/ingest.py
Reverts BEIS-Digital-Services/RedBox-AWS#91
=> Revert "test replacement for vectorstore.add_documents"

django_app/redbox_app/redbox_core/views/document_views.py, django_app/redbox_app/settings.py, django_app/redbox_app/templates/accessibility-statement.html, django_app/redbox_app/templates/base.html, django_app/redbox_app/templates/documents.html, django_app/redbox_app/templates/homepage.html, django_app/redbox_app/templates/privacy-notice.html, django_app/redbox_app/templates/support.html
=> Contact_info_updates

redbox-core/redbox/loader/ingester.py
=> re-auth vectorstore

redbox-core/redbox/loader/ingester.py
=> try vectorestore re-auth with AWS4Auth

django_app/poetry.lock, django_app/pyproject.toml
=> adding requests_aws4auth to requirements

redbox-core/redbox/loader/ingester.py
=> Conform to requests' auth using wrapper

redbox-core/redbox/loader/ingester.py
=> update custom auth wrapper

redbox-core/redbox/loader/ingester.py
=> returns only headers dictionary in auth wrapper

django_app/redbox_app/redbox_core/models.py
=> add logic for building s3 keys

django_app/redbox_app/redbox_core/models.py
=> correct field name in filter

django_app/redbox_app/redbox_core/models.py
=> alter filter to use email

django_app/redbox_app/redbox_core/views/document_views.py
=> Attempt InMemoryUploadedFile Wrapping

django_app/redbox_app/redbox_core/views/document_views.py
=> update file upload validation

django_app/redbox_app/redbox_core/views/document_views.py
=> log files to validate filepath

django_app/redbox_app/redbox_core/views/document_views.py
=> resolve annotation value error

django_app/redbox_app/redbox_core/views/document_views.py
=> switch to iendswith

django_app/redbox_app/redbox_core/views/document_views.py
=> normalise file name for matching

django_app/redbox_app/templates/documents.html
=> replace gpt-4o reference on documents page

django_app/redbox_app/redbox_core/views/document_views.py
=> update file name normalisation

django_app/redbox_app/redbox_core/views/document_views.py
=> fix unterminated f-string

django_app/redbox_app/templates/base.html
=> use correct jinja2 syntax for default link

django_app/redbox_app/redbox_core/views/chat_views.py, django_app/redbox_app/redbox_core/views/demographics_views.py, django_app/redbox_app/redbox_core/views/document_views.py, django_app/redbox_app/redbox_core/views/info_views.py, django_app/redbox_app/redbox_core/views/misc_views.py, django_app/redbox_app/settings.py, django_app/redbox_app/templates/accessibility-statement.html, django_app/redbox_app/templates/base.html, django_app/redbox_app/templates/documents.html, django_app/redbox_app/templates/support.html
=> Deploy to staging

django_app/redbox_app/redbox_core/views/chat_views.py, django_app/redbox_app/redbox_core/views/demographics_views.py, django_app/redbox_app/redbox_core/views/document_views.py, django_app/redbox_app/redbox_core/views/info_views.py, django_app/redbox_app/redbox_core/views/misc_views.py, django_app/redbox_app/settings.py, django_app/redbox_app/templates/accessibility-statement.html, django_app/redbox_app/templates/base.html, django_app/redbox_app/templates/documents.html, django_app/redbox_app/templates/support.html
=> Deploy to production

.env.example, django_app/redbox_app/settings.py
=> handle staging okta domain

django_app/redbox_app/redbox_core/consumers.py
=> adding more logs

django_app/redbox_app/redbox_core/consumers.py
=> wrapping synchronous database queries

django_app/frontend/src/js/web-components/chats/chat-message.js, django_app/redbox_app/redbox_core/consumers.py
=> resetting websocket connections
